### ISSUE TITLE
[Feat]#10 - UIButton 구현

### ISSUE THREAD

**Issue by VesselWheel** [NBCamp-KickGoing-3team/Kick_Going#10]
## To-do

- [ ] 킥보드 아이콘을 눌렀을 때 데이터 정보 저장
- [ ] 저장된 정보를 register 영역으로 데이터 전송
- [ ] 킥보드, 자전거 아이콘을 누르기 여부에 따라 지도에 킥보드와 자전거 아이콘 보여주기/제거하기
- [ ] 위치 검색 기능 추가하기
