### ISSUE TITLE
[Feat]#21 - Register data를 MyPage에 기록 

### ISSUE THREAD

**Issue by BINDUNGLIFE** [NBCamp-KickGoing-3team/Kick_Going#21]
## To-do

- [x] 데이터 저장소 생성 DataStore
- [x] 델리게이트 프로토콜 정의
- [x] 델리게이트 구현
- [x]  데이터 전달 : RegisterViewController에서 사용자가 킥보드를 등록하고 '확인' 버튼을 누르면, 델리게이트 메서드를 호출하여 MyPageViewController에 정보를 전달
- [x] 뷰 컨트롤러 간 데이터 공유
- [x]  탭 전환 : RegisterViewController에서 킥보드 등록이 완료되면 사용자를 MyPageViewController 탭으로 전환
